a=10;
b=20;
c=a++ + ++b;
console.log("The value of c is: " + c);
sum=a+b;
console.log("The sum of a and b is: " + sum);
difference=b-a;
console.log("The difference of b and a is: " + difference);
product=a*b;
console.log("The product of a and b is: " + product);
quotient=b/a;
console.log("The quotient of b divided by a is: " + quotient);
remainder=b%a;
console.log("The remainder of b divided by a is: " + remainder);
power=a**2;
console.log("The value of a squared is: " + power);
sqrt=Math.sqrt(b);
console.log("The square root of b is: " + sqrt);
incrementedA=++a;
console.log("The value of a after incrementing is: " + incrementedA);
decrementedB=--b;
console.log("The value of b after decrementing is: " + decrementedB);
maxValue=Math.max(a,b);
console.log("The maximum value between a and b is: " + maxValue);
minValue=Math.min(a,b);
console.log("The minimum value between a and b is: " + minValue);
randomValue=Math.random()*100;
console.log("A random value between 0 and 100 is: " + randomValue);
roundedValue=Math.round(randomValue);
console.log("The rounded value of the random number is: " + roundedValue);
fixedValue=randomValue.toFixed(2);
console.log("The random number fixed to 2 decimal places is: " + fixedValue);
absoluteValue=Math.abs(a-b);
console.log("The absolute value of the difference between a and b is: " + absoluteValue);
logValue=Math.log(a);
console.log("The natural logarithm of a is: " + logValue);
expValue=Math.exp(1);
console.log("The value of e raised to the power of 1 is: " + expValue);
sinValue=Math.sin(a);
console.log("The sine of a (in radians) is: " + sinValue);
cosValue=Math.cos(b);
console.log("The cosine of b (in radians) is: " + cosValue);
tanValue=Math.tan(a);
console.log("The tangent of a (in radians) is: " + tanValue);
floorValue=Math.floor(randomValue);
console.log("The floor value of the random number is: " + floorValue);
ceilValue=Math.ceil(randomValue);
console.log("The ceiling value of the random number is: " + ceilValue);
truncValue=Math.trunc(randomValue);
console.log("The truncated value of the random number is: " + truncValue);
signValue=Math.sign(a-b);
console.log("The sign of the difference between a and b is: " + signValue);